[2025-03-25T10:33:30.296+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-25T10:33:30.318+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag._choose_best_model scheduled__2025-03-17T00:00:00+00:00 [queued]>
[2025-03-25T10:33:30.327+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag._choose_best_model scheduled__2025-03-17T00:00:00+00:00 [queued]>
[2025-03-25T10:33:30.328+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-25T10:33:30.344+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): _choose_best_model> on 2025-03-17 00:00:00+00:00
[2025-03-25T10:33:30.351+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T10:33:30.352+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', '_choose_best_model', 'scheduled__2025-03-17T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpe75sdlhb']
[2025-03-25T10:33:30.352+0000] {standard_task_runner.py:63} INFO - Started process 104 to run task
[2025-03-25T10:33:30.353+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask _choose_best_model
[2025-03-25T10:33:30.404+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag._choose_best_model scheduled__2025-03-17T00:00:00+00:00 [running]> on host 7ed0592ccd5e
[2025-03-25T10:33:30.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='_choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-17T00:00:00+00:00'
[2025-03-25T10:33:30.483+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-25T10:33:30.497+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-25T10:33:30.506+0000] {python.py:237} INFO - Done. Returned value was: inaccurate
[2025-03-25T10:33:30.507+0000] {branch.py:36} INFO - Branch into inaccurate
[2025-03-25T10:33:30.508+0000] {skipmixin.py:178} INFO - Following branch inaccurate
[2025-03-25T10:33:30.526+0000] {skipmixin.py:246} INFO - Skipping tasks [('accurate', -1)]
[2025-03-25T10:33:30.559+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-25T10:33:30.579+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=_choose_best_model, run_id=scheduled__2025-03-17T00:00:00+00:00, execution_date=20250317T000000, start_date=20250325T103330, end_date=20250325T103330
[2025-03-25T10:33:30.608+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-25T10:33:30.634+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-25T10:33:30.638+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
