[2025-03-25T10:33:30.294+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-25T10:33:30.315+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag._choose_best_model scheduled__2025-03-24T00:00:00+00:00 [queued]>
[2025-03-25T10:33:30.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag._choose_best_model scheduled__2025-03-24T00:00:00+00:00 [queued]>
[2025-03-25T10:33:30.326+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-03-25T10:33:30.342+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): _choose_best_model> on 2025-03-24 00:00:00+00:00
[2025-03-25T10:33:30.347+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=102) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-25T10:33:30.349+0000] {standard_task_runner.py:63} INFO - Started process 103 to run task
[2025-03-25T10:33:30.349+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_dag', '_choose_best_model', 'scheduled__2025-03-24T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp4xleihkf']
[2025-03-25T10:33:30.350+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask _choose_best_model
[2025-03-25T10:33:30.399+0000] {task_command.py:426} INFO - Running <TaskInstance: my_dag._choose_best_model scheduled__2025-03-24T00:00:00+00:00 [running]> on host 7ed0592ccd5e
[2025-03-25T10:33:30.485+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='_choose_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-03-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-24T00:00:00+00:00'
[2025-03-25T10:33:30.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-25T10:33:30.501+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-25T10:33:30.511+0000] {python.py:237} INFO - Done. Returned value was: accurate
[2025-03-25T10:33:30.512+0000] {branch.py:36} INFO - Branch into accurate
[2025-03-25T10:33:30.512+0000] {skipmixin.py:178} INFO - Following branch accurate
[2025-03-25T10:33:30.527+0000] {skipmixin.py:246} INFO - Skipping tasks [('inaccurate', -1)]
[2025-03-25T10:33:30.556+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-25T10:33:30.577+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=_choose_best_model, run_id=scheduled__2025-03-24T00:00:00+00:00, execution_date=20250324T000000, start_date=20250325T103330, end_date=20250325T103330
[2025-03-25T10:33:30.604+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-03-25T10:33:30.628+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-25T10:33:30.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
